<Project>

  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsNotAsErrors>NU1901;NU1902;NU1903;NU1904</WarningsNotAsErrors>
    <Version>0.1.2</Version>
  </PropertyGroup>

  <PropertyGroup>
    <TestcontainersVersion>4.14.0</TestcontainersVersion>
    <TestcontainersTestVersion Condition="'$(TestcontainersTestVersion)' == ''">$(TestcontainersVersion)</TestcontainersTestVersion>
  </PropertyGroup>

</Project>
